export const rab = [
  { id: 1, Name: "Petr", Familia: "Pervi", Rabota: "Razrabotchik",
    Iziki: ["Js", "c++"], Zp: 120000, Posta: "Petr@mail.ru",
    Data: "2023-09-23", Otdel: { id: 1, name: "IT" } },
  { id: 2, Name: "Ivan", Familia: "Sidorov", Rabota: "Fr-razrabochik",
    Iziki: ["Js", "React", "CSS"], Zp: 135000, Posta: "Ivan@mail.ru",
    Data: "2022-03-15", Otdel: { id: 1, name: "IT" } },
  { id: 3, Name: "Anna", Familia: "Kuznetsova", Rabota: "Bac-razrabochik",
    Iziki: ["Python", "Django", "SQL"], Zp: 150000, Posta: "Anna@mail.ru",
    Data: "2021-08-11", Otdel: { id: 1, name: "IT" } },
  { id: 4, Name: "Sergey", Familia: "Morozov", Rabota: "Ingener",
    Iziki: ["Docker", "Kubernetes", "Bash"], Zp: 170000, Posta: "Sergey@mail.ru",
    Data: "2020-05-20", Otdel: { id: 1, name: "IT" } },
  { id: 5, Name: "Elena", Familia: "Volkova", Rabota: "Tester",
    Iziki: ["Selenium", "Python"], Zp: 95000, Posta: "Elena@mail.ru",
    Data: "2023-12-01", Otdel: { id: 1, name: "IT" } },
  { id: 6, Name: "Dmitry", Familia: "Novikov", Rabota: "Analitik",
    Iziki: ["SQL", "Excel", "Python"], Zp: 110000, Posta: "Dmitry@mail.ru",
    Data: "2022-07-19", Otdel: { id: 2, name: "Analytics" } },
  { id: 7, Name: "Olga", Familia: "Fedorova", Rabota: "Project Manager",
    Iziki: ["Jira", "Scrum"], Zp: 160000, Posta: "Olga@mail.ru",
    Data: "2019-04-30", Otdel: { id: 3, name: "Management" } },
  { id: 8, Name: "Alexey", Familia: "Popov", Rabota: "Disaner",
    Iziki: ["Figma", "Photoshop"], Zp: 105000, Posta: "Alexey@mail.ru",
    Data: "2023-06-01", Otdel: { id: 4, name: "Design" } },
  { id: 9, Name: "Maria", Familia: "Sokolova", Rabota: "HR",
    Iziki: ["Recruiting", "Excel"], Zp: 85000, Posta: "Maria@mail.ru",
    Data: "2021-02-22", Otdel: { id: 5, name: "HR" } },
  { id: 10, Name: "Nikolay", Familia: "Lebedev", Rabota: "Sis adm",
    Iziki: ["Linux", "Bash", "Windows"], Zp: 100000, Posta: "Nikolay@mail.ru",
    Data: "2020-10-17", Otdel: { id: 1, name: "IT" } },
  { id: 11, Name: "Tatiana", Familia: "Orlova", Rabota: "Data Scientist",
    Iziki: ["Python", "ML", "TensorFlow"], Zp: 200000, Posta: "Tatiana@mail.ru",
    Data: "2022-09-03", Otdel: { id: 2, name: "Analytics" } },
  { id: 12, Name: "Andrey", Familia: "Kozlov", Rabota: "Fullstack-razrabochik",
    Iziki: ["Js", "Node.js", "React", "SQL"], Zp: 180000, Posta: "Andrey@mail.ru",
    Data: "2018-11-25", Otdel: { id: 1, name: "IT" } },
  { id: 13, Name: "Svetlana", Familia: "Pavlova", Rabota: "Meneger",
    Iziki: ["CRM", "Excel"], Zp: 90000, Posta: "Svetlana@mail.ru",
    Data: "2023-08-07", Otdel: { id: 6, name: "Sales" } },
  { id: 14, Name: "Vladimir", Familia: "Stepanov", Rabota: "Buxgalter",
    Iziki: ["Markdown", "Confluence"], Zp: 88000, Posta: "Vladimir@mail.ru",
    Data: "2021-05-14", Otdel: { id: 1, name: "IT" } },
  { id: 15, Name: "Ekaterina", Familia: "Nikolaeva", Rabota: "Analitik",
    Iziki: ["SQL", "BPMN", "Excel"], Zp: 125000, Posta: "Ekaterina@mail.ru",
    Data: "2022-12-28", Otdel: { id: 2, name: "Analytics" } }
];

export const vacansi = [
  { id: 1, Dolznost: "Disaner", MinZp: 80000, MaxZp: 120000, Otdel: "IT",
    Iziki: ["Js", "C#"], Do: "2030-01-01", Status: "V poeske" },
  { id: 2, Dolznost: "Frontend-razrabochik", MinZp: 100000, MaxZp: 160000, Otdel: "IT",
    Iziki: ["Js", "React", "CSS"], Do: "2029-06-15", Status: "Otkryta" },
  { id: 3, Dolznost: "Backend-razrabochik", MinZp: 120000, MaxZp: 200000, Otdel: "IT",
    Iziki: ["Python", "Django", "SQL"], Do: "2029-03-20", Status: "Otkryta" },
  { id: 4, Dolznost: "Ingener", MinZp: 150000, MaxZp: 220000, Otdel: "IT",
    Iziki: ["Docker", "Kubernetes", "Bash"], Do: "2028-12-01", Status: "Zakryta" },
  { id: 5, Dolznost: "Tester", MinZp: 70000, MaxZp: 110000, Otdel: "IT",
    Iziki: ["Selenium", "Python"], Do: "2029-09-10", Status: "V poeske" },
  { id: 6, Dolznost: "Analitik", MinZp: 90000, MaxZp: 140000, Otdel: "Analytics",
    Iziki: ["SQL", "Excel", "Python"], Do: "2030-02-28", Status: "Otkryta" },
  { id: 7, Dolznost: "Project Manager", MinZp: 130000, MaxZp: 190000, Otdel: "Management",
    Iziki: ["Jira", "Scrum"], Do: "2028-11-05", Status: "Zakryta" },
  { id: 8, Dolznost: "Disaner", MinZp: 85000, MaxZp: 130000, Otdel: "Design",
    Iziki: ["Figma", "Photoshop"], Do: "2029-07-22", Status: "V poeske" },
  { id: 9, Dolznost: "HR", MinZp: 60000, MaxZp: 95000, Otdel: "HR",
    Iziki: ["Recruiting", "Excel"], Do: "2030-04-01", Status: "Otkryta" },
  { id: 10, Dolznost: "Sis adm", MinZp: 80000, MaxZp: 120000, Otdel: "IT",
    Iziki: ["Linux", "Bash", "Windows"], Do: "2029-01-15", Status: "Zakryta" },
  { id: 11, Dolznost: "Data Scientist", MinZp: 160000, MaxZp: 250000, Otdel: "Analytics",
    Iziki: ["Python", "ML", "TensorFlow"], Do: "2028-10-30", Status: "Otkryta" },
  { id: 12, Dolznost: "Fullstack-razrabochik", MinZp: 140000, MaxZp: 210000, Otdel: "IT",
    Iziki: ["Js", "Node.js", "React", "SQL"], Do: "2029-05-19", Status: "V poeske" },
  { id: 13, Dolznost: "Meneger", MinZp: 70000, MaxZp: 150000, Otdel: "Sales",
    Iziki: ["CRM", "Excel"], Do: "2030-03-10", Status: "Otkryta" },
  { id: 14, Dolznost: "Pisatel", MinZp: 65000, MaxZp: 100000, Otdel: "IT",
    Iziki: ["Markdown", "Confluence"], Do: "2029-08-25", Status: "Zakryta" },
  { id: 15, Dolznost: "Analitik", MinZp: 100000, MaxZp: 150000, Otdel: "Analytics",
    Iziki: ["SQL", "BPMN", "Excel"], Do: "2030-05-12", Status: "V poeske" }
];

export const otkliki = [
  { id: 1, RabId: 1, VacansiId: 3, DataOtk: "2024-01-15", Status: "Na rassmotrenii", Koment: "Otpravil rezyume", Rezyume: "petr_cv.pdf", Ocenka: 4 },
  { id: 2, RabId: 1, VacansiId: 12, DataOtk: "2024-02-03", Status: "Priglashen", Koment: "Naznacheno sobesedovanie", Rezyume: "petr_cv_v2.pdf", Ocenka: 5 },
  { id: 3, RabId: 2, VacansiId: 2, DataOtk: "2024-01-20", Status: "Otkazan", Koment: "Ne podhodit po opytu", Rezyume: "ivan_cv.pdf", Ocenka: 2 },
  { id: 4, RabId: 3, VacansiId: 3, DataOtk: "2024-02-10", Status: "Priglashen", Koment: "Proshel perviy etap", Rezyume: "anna_cv.pdf", Ocenka: 5 },
  { id: 5, RabId: 4, VacansiId: 4, DataOtk: "2024-01-05", Status: "Na rassmotrenii", Koment: "Ozhidaet otveta", Rezyume: "sergey_cv.pdf", Ocenka: 4 },
  { id: 6, RabId: 5, VacansiId: 5, DataOtk: "2024-02-18", Status: "Priglashen", Koment: "Testovoe zadanie otpravleno", Rezyume: "elena_cv.pdf", Ocenka: 4 },
  { id: 7, RabId: 6, VacansiId: 6, DataOtk: "2024-01-28", Status: "Otkazan", Koment: "Vakansiya zakryta", Rezyume: "dmitry_cv.pdf", Ocenka: 3 },
  { id: 8, RabId: 7, VacansiId: 7, DataOtk: "2024-02-01", Status: "Na rassmotrenii", Koment: "Zhdem resheniya rukovodstva", Rezyume: "olga_cv.pdf", Ocenka: 5 },
  { id: 9, RabId: 8, VacansiId: 8, DataOtk: "2024-02-14", Status: "Priglashen", Koment: "Portfolio odobreno", Rezyume: "alexey_cv.pdf", Ocenka: 5 },
  { id: 10, RabId: 9, VacansiId: 9, DataOtk: "2024-01-12", Status: "Otkazan", Koment: "Kandidat otkazalsya", Rezyume: "maria_cv.pdf", Ocenka: 3 },
  { id: 11, RabId: 10, VacansiId: 10, DataOtk: "2024-02-07", Status: "Na rassmotrenii", Koment: "Proverka rekomendaciy", Rezyume: "nikolay_cv.pdf", Ocenka: 4 },
  { id: 12, RabId: 11, VacansiId: 11, DataOtk: "2024-02-20", Status: "Priglashen", Koment: "Offer gotovitsya", Rezyume: "tatiana_cv.pdf", Ocenka: 5 },
  { id: 13, RabId: 12, VacansiId: 12, DataOtk: "2024-01-25", Status: "Priglashen", Koment: "Uspeshnoe sobesedovanie", Rezyume: "andrey_cv.pdf", Ocenka: 5 },
  { id: 14, RabId: 13, VacansiId: 13, DataOtk: "2024-02-11", Status: "Otkazan", Koment: "Ne proshel finalnyy etap", Rezyume: "sveta_cv.pdf", Ocenka: 2 },
  { id: 15, RabId: 14, VacansiId: 14, DataOtk: "2024-02-16", Status: "Na rassmotrenii", Koment: "Ozhidaet testovoe", Rezyume: "vladimir_cv.pdf", Ocenka: 3 },
  { id: 16, RabId: 15, VacansiId: 15, DataOtk: "2024-02-22", Status: "Priglashen", Koment: "Soglasovanie usloviy", Rezyume: "ekaterina_cv.pdf", Ocenka: 5 },
  { id: 17, RabId: 3, VacansiId: 11, DataOtk: "2024-01-30", Status: "Na rassmotrenii", Koment: "Otklik na smezhnuyu rol", Rezyume: "anna_cv_v2.pdf", Ocenka: 4 },
  { id: 18, RabId: 12, VacansiId: 3, DataOtk: "2024-02-05", Status: "Otkazan", Koment: "Zarplatnye ozhidaniya vyshe", Rezyume: "andrey_cv_v2.pdf", Ocenka: 3 },
  { id: 19, RabId: 2, VacansiId: 12, DataOtk: "2024-02-19", Status: "Priglashen", Koment: "Rekomendovan rukovoditelem", Rezyume: "ivan_cv_v2.pdf", Ocenka: 5 },
  { id: 20, RabId: 11, VacansiId: 6, DataOtk: "2024-02-24", Status: "Na rassmotrenii", Koment: "Perviy otklik v otdel", Rezyume: "tatiana_cv.pdf", Ocenka: 4 }
];
